plugins {
    id 'fabric-loom' version '1.17-SNAPSHOT'
    id 'maven-publish'
}

version = "1.3.0-26.2"
group = "com.serversniffer"

repositories {
    maven { url = "https://maven.fabricmc.net/" }
    maven { url = "https://maven.meteordev.org/releases" }
    maven { url = "https://maven.meteordev.org/snapshots" }
    maven { url = "https://maven.terraformersmc.com/releases/" }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:26.2"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:0.19.3"
    modImplementation "net.fabricmc:fabric-api:0.161.0+26.2"

    modImplementation("meteordevelopment:meteor-client:26.2-SNAPSHOT") {
        exclude group: "net.fabricmc.fabric-api"
    }
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

def targetJavaVersion = 25
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = targetJavaVersion
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(targetJavaVersion) }
    withSourcesJar()
}
